# Shared definition block
shared:
  # Source: https://hub.docker.com/repository/docker/schofr/cronagent
  image: schofr/cronagent

jobs:
    main:
        requires: [~commit]
        image: docker.io/schofr/cronagent:dev
        steps:
            - init: echo hello
            - build: docker build -f Dockerfile -t schofr/cronagent:dev .
